name: Build workflow

on:
  push:
  pull_request:

jobs:
  build-and-lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install latest LTS version of Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          check-latest: true
      - name: Clean install
        run: npm ci
      - name: Build scripts
        run: npm run build
      - name: Run ESLint
        run: npm run lint
